/**
 * A QR encoder, written out rather than installed.
 *
 * The room code is four letters and the join URL is under a hundred bytes, so
 * the whole of QR is not needed: byte mode, error correction level M, versions
 * 1 through 10. That is a few hundred lines and no third dependency in a build
 * that has exactly two — and a projector has to render this without a CDN,
 * because the room the game is played in usually has worse wifi than the
 * phones scanning it.
 *
 * Level M is deliberate. A projected code is scanned off a bright, low-contrast
 * surface from four metres by four phones at once; L saves a version and loses
 * the redundancy exactly where the reads are worst.
 *
 * The structure follows ISO/IEC 18004. `test/qr.test.ts` pins every matrix
 * against goldens generated by a reference encoder, so the tables below are
 * checked rather than trusted.
 */

/** A square grid of dark/light modules, quiet zone not included. */
export interface QrMatrix {
  size: number
  /** `modules[y][x]` — true is dark. */
  modules: boolean[][]
}

/** Block structure for error correction level M, versions 1–10. */
const BLOCKS: Record<
  number,
  { ec: number; group1: number; data1: number; group2: number; data2: number }
> = {
  1: { ec: 10, group1: 1, data1: 16, group2: 0, data2: 0 },
  2: { ec: 16, group1: 1, data1: 28, group2: 0, data2: 0 },
  3: { ec: 26, group1: 1, data1: 44, group2: 0, data2: 0 },
  4: { ec: 18, group1: 2, data1: 32, group2: 0, data2: 0 },
  5: { ec: 24, group1: 2, data1: 43, group2: 0, data2: 0 },
  6: { ec: 16, group1: 4, data1: 27, group2: 0, data2: 0 },
  7: { ec: 18, group1: 4, data1: 31, group2: 0, data2: 0 },
  8: { ec: 22, group1: 2, data1: 38, group2: 2, data2: 39 },
  9: { ec: 22, group1: 3, data1: 36, group2: 2, data2: 37 },
  10: { ec: 26, group1: 4, data1: 43, group2: 1, data2: 44 },
}

/** Row and column centres of the alignment patterns, by version. */
const ALIGNMENT: Record<number, number[]> = {
  1: [],
  2: [6, 18],
  3: [6, 22],
  4: [6, 26],
  5: [6, 30],
  6: [6, 34],
  7: [6, 22, 38],
  8: [6, 24, 42],
  9: [6, 26, 46],
  10: [6, 28, 50],
}

const MAX_VERSION = 10

/* ── GF(256), the field the error correction lives in ───────────────── */

const EXP = new Uint8Array(512)
const LOG = new Uint8Array(256)

function buildTables() {
  let x = 1
  for (let i = 0; i < 255; i++) {
    EXP[i] = x
    LOG[x] = i
    x <<= 1
    if (x & 0x100) x ^= 0x11d // the primitive polynomial QR is defined over
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]
}
buildTables()

function mul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]
}

/** The generator polynomial for `n` error correction codewords. */
function generator(n: number): number[] {
  let poly = [1]
  for (let i = 0; i < n; i++) {
    const next = new Array<number>(poly.length + 1).fill(0)
    // Index 0 is the highest power, so multiplying by x keeps the index and
    // multiplying by the root moves it down one.
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j]
      next[j + 1] ^= mul(poly[j], EXP[i])
    }
    poly = next
  }
  return poly
}

/** The remainder of `data` divided by the generator — the EC codewords. */
function errorCorrection(data: number[], n: number): number[] {
  const gen = generator(n)
  const rem = new Array<number>(n).fill(0)
  for (const byte of data) {
    const factor = byte ^ rem[0]
    rem.shift()
    rem.push(0)
    for (let i = 0; i < n; i++) rem[i] ^= mul(gen[i + 1], factor)
  }
  return rem
}

/* ── Data ───────────────────────────────────────────────────────────── */

function utf8(text: string): number[] {
  return Array.from(new TextEncoder().encode(text))
}

function capacity(version: number): number {
  const b = BLOCKS[version]
  return b.group1 * b.data1 + b.group2 * b.data2
}

/** The smallest version that holds the payload, header included. */
function pickVersion(bytes: number): number {
  for (let v = 1; v <= MAX_VERSION; v++) {
    // 4 bits of mode, then 8 or 16 bits of length.
    const header = v <= 9 ? 12 : 20
    if (capacity(v) * 8 >= header + bytes * 8) return v
  }
  throw new Error(`QR: ${bytes} bytes is more than version ${MAX_VERSION}-M holds`)
}

/** Mode, length, payload, terminator, padding — one codeword array. */
function codewords(bytes: number[], version: number): number[] {
  const bits: number[] = []
  const push = (value: number, width: number) => {
    for (let i = width - 1; i >= 0; i--) bits.push((value >>> i) & 1)
  }

  push(0b0100, 4) // byte mode
  push(bytes.length, version <= 9 ? 8 : 16)
  for (const b of bytes) push(b, 8)

  const total = capacity(version) * 8
  for (let i = 0; i < 4 && bits.length < total; i++) bits.push(0) // terminator
  while (bits.length % 8 !== 0) bits.push(0)

  const out: number[] = []
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j]
    out.push(byte)
  }
  // The two pad bytes the standard names, alternating.
  for (let i = 0; out.length < capacity(version); i++) out.push(i % 2 === 0 ? 0xec : 0x11)
  return out
}

/**
 * Split into blocks, add error correction, interleave.
 *
 * The interleave is the point of the exercise: a scratch or a thumb across the
 * printed code damages consecutive modules, and spreading each block's
 * codewords across the whole symbol turns one fatal wound into a survivable
 * one in every block.
 */
function interleave(data: number[], version: number): number[] {
  const b = BLOCKS[version]
  const blocks: number[][] = []
  const ecBlocks: number[][] = []

  let at = 0
  for (let i = 0; i < b.group1 + b.group2; i++) {
    const size = i < b.group1 ? b.data1 : b.data2
    const block = data.slice(at, at + size)
    at += size
    blocks.push(block)
    ecBlocks.push(errorCorrection(block, b.ec))
  }

  const out: number[] = []
  const longest = Math.max(b.data1, b.data2)
  for (let i = 0; i < longest; i++) {
    for (const block of blocks) if (i < block.length) out.push(block[i])
  }
  for (let i = 0; i < b.ec; i++) {
    for (const block of ecBlocks) out.push(block[i])
  }
  return out
}

/* ── The symbol ─────────────────────────────────────────────────────── */

interface Canvas {
  size: number
  modules: boolean[][]
  /** Function patterns are fixed: neither data nor the mask may touch them. */
  reserved: boolean[][]
}

function blank(version: number): Canvas {
  const size = version * 4 + 17
  return {
    size,
    modules: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    reserved: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  }
}

function setFunction(c: Canvas, x: number, y: number, dark: boolean) {
  if (x < 0 || y < 0 || x >= c.size || y >= c.size) return
  c.modules[y][x] = dark
  c.reserved[y][x] = true
}

function drawFinder(c: Canvas, cx: number, cy: number) {
  for (let dy = -4; dy <= 4; dy++) {
    for (let dx = -4; dx <= 4; dx++) {
      const dist = Math.max(Math.abs(dx), Math.abs(dy))
      setFunction(c, cx + dx, cy + dy, dist !== 2 && dist !== 4)
    }
  }
}

function drawAlignment(c: Canvas, cx: number, cy: number) {
  for (let dy = -2; dy <= 2; dy++) {
    for (let dx = -2; dx <= 2; dx++) {
      setFunction(c, cx + dx, cy + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1)
    }
  }
}

/** Level M is `00`; the five bits are protected by a BCH(15,5) code. */
function formatBits(mask: number): number {
  const data = (0b00 << 3) | mask
  let rem = data
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537)
  return (((data << 10) | rem) ^ 0x5412) >>> 0
}

function drawFormat(c: Canvas, mask: number) {
  const bits = formatBits(mask)
  const bit = (i: number) => ((bits >>> i) & 1) === 1

  for (let i = 0; i <= 5; i++) setFunction(c, 8, i, bit(i))
  setFunction(c, 8, 7, bit(6))
  setFunction(c, 8, 8, bit(7))
  setFunction(c, 7, 8, bit(8))
  for (let i = 9; i < 15; i++) setFunction(c, 14 - i, 8, bit(i))

  for (let i = 0; i < 8; i++) setFunction(c, c.size - 1 - i, 8, bit(i))
  for (let i = 8; i < 15; i++) setFunction(c, 8, c.size - 15 + i, bit(i))

  setFunction(c, 8, c.size - 8, true) // the dark module, always
}

/** Versions 7 and up carry their own version number, BCH(18,6) protected. */
function drawVersion(c: Canvas, version: number) {
  if (version < 7) return
  let rem = version
  for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25)
  const bits = ((version << 12) | rem) >>> 0
  for (let i = 0; i < 18; i++) {
    const dark = ((bits >>> i) & 1) === 1
    const a = c.size - 11 + (i % 3)
    const b = Math.floor(i / 3)
    setFunction(c, a, b, dark)
    setFunction(c, b, a, dark)
  }
}

function drawPatterns(c: Canvas, version: number) {
  for (let i = 0; i < c.size; i++) {
    setFunction(c, 6, i, i % 2 === 0)
    setFunction(c, i, 6, i % 2 === 0)
  }

  drawFinder(c, 3, 3)
  drawFinder(c, c.size - 4, 3)
  drawFinder(c, 3, c.size - 4)

  const centres = ALIGNMENT[version]
  for (const cy of centres) {
    for (const cx of centres) {
      // The three corners already hold finder patterns.
      const corner =
        (cx === 6 && cy === 6) ||
        (cx === 6 && cy === c.size - 7) ||
        (cx === c.size - 7 && cy === 6)
      if (!corner) drawAlignment(c, cx, cy)
    }
  }

  drawVersion(c, version)
  drawFormat(c, 0) // reserves the area; rewritten once the mask is chosen
}

/** Two modules wide, snaking bottom-right to top-left, skipping the timing column. */
function drawData(c: Canvas, data: number[]) {
  let i = 0
  for (let right = c.size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5
    for (let vert = 0; vert < c.size; vert++) {
      for (let j = 0; j < 2; j++) {
        const x = right - j
        const upward = ((right + 1) & 2) === 0
        const y = upward ? c.size - 1 - vert : vert
        if (!c.reserved[y][x] && i < data.length * 8) {
          c.modules[y][x] = ((data[i >>> 3] >>> (7 - (i & 7))) & 1) === 1
          i++
        }
      }
    }
  }
}

const MASKS: ((x: number, y: number) => boolean)[] = [
  (x, y) => (x + y) % 2 === 0,
  (_x, y) => y % 2 === 0,
  (x) => x % 3 === 0,
  (x, y) => (x + y) % 3 === 0,
  (x, y) => (Math.floor(y / 2) + Math.floor(x / 3)) % 2 === 0,
  (x, y) => ((x * y) % 2) + ((x * y) % 3) === 0,
  (x, y) => (((x * y) % 2) + ((x * y) % 3)) % 2 === 0,
  (x, y) => (((x + y) % 2) + ((x * y) % 3)) % 2 === 0,
]

function applyMask(c: Canvas, mask: number) {
  const fn = MASKS[mask]
  for (let y = 0; y < c.size; y++) {
    for (let x = 0; x < c.size; x++) {
      if (!c.reserved[y][x] && fn(x, y)) c.modules[y][x] = !c.modules[y][x]
    }
  }
}

/* ── Choosing the mask ──────────────────────────────────────────────── */

const N1 = 3
const N2 = 3
const N3 = 40
const N4 = 10

/** Runs of five or more of one colour, along every row and every column. */
function penaltyRuns(c: Canvas): number {
  let points = 0
  for (let a = 0; a < c.size; a++) {
    let rowRun = 0
    let colRun = 0
    let lastRow: boolean | null = null
    let lastCol: boolean | null = null
    for (let b = 0; b < c.size; b++) {
      const inRow = c.modules[a][b]
      if (inRow === lastRow) rowRun++
      else {
        if (rowRun >= 5) points += N1 + (rowRun - 5)
        lastRow = inRow
        rowRun = 1
      }

      const inCol = c.modules[b][a]
      if (inCol === lastCol) colRun++
      else {
        if (colRun >= 5) points += N1 + (colRun - 5)
        lastCol = inCol
        colRun = 1
      }
    }
    if (rowRun >= 5) points += N1 + (rowRun - 5)
    if (colRun >= 5) points += N1 + (colRun - 5)
  }
  return points
}

/** Solid 2×2 blocks. */
function penaltyBlocks(c: Canvas): number {
  let points = 0
  for (let y = 0; y < c.size - 1; y++) {
    for (let x = 0; x < c.size - 1; x++) {
      const sum =
        +c.modules[y][x] + +c.modules[y][x + 1] + +c.modules[y + 1][x] + +c.modules[y + 1][x + 1]
      if (sum === 0 || sum === 4) points++
    }
  }
  return points * N2
}

/**
 * Anything that reads like a finder pattern where there isn't one: the
 * 1:1:3:1:1 run with four light modules on one side of it, which is exactly
 * what a scanner hunts for to locate the symbol.
 */
function penaltyFinderish(c: Canvas): number {
  let points = 0
  for (let a = 0; a < c.size; a++) {
    let row = 0
    let col = 0
    for (let b = 0; b < c.size; b++) {
      row = ((row << 1) & 0x7ff) | +c.modules[a][b]
      col = ((col << 1) & 0x7ff) | +c.modules[b][a]
      if (b >= 10) {
        if (row === 0x5d0 || row === 0x05d) points++
        if (col === 0x5d0 || col === 0x05d) points++
      }
    }
  }
  return points * N3
}

/** How far the proportion of dark modules strays from half, in steps of 5%. */
function penaltyBalance(c: Canvas): number {
  let dark = 0
  for (const row of c.modules) for (const m of row) if (m) dark++
  const total = c.size * c.size
  return Math.abs(Math.ceil(((dark * 100) / total) / 5) - 10) * N4
}

/** The standard's four penalties. Lowest score wins; ties go to the lower mask. */
function penalty(c: Canvas): number {
  return penaltyRuns(c) + penaltyBlocks(c) + penaltyFinderish(c) + penaltyBalance(c)
}

/**
 * Encode `text` as a QR symbol.
 *
 * The mask is chosen the way the standard says to — all eight drawn, each
 * scored, the lowest kept — rather than fixed, because a fixed mask on a
 * projected code is how you end up with a large light field a phone reads as
 * the wall behind it.
 */
export function encodeQr(text: string): QrMatrix {
  const bytes = utf8(text)
  const version = pickVersion(bytes.length)
  const data = interleave(codewords(bytes, version), version)

  let best: Canvas | null = null
  let bestScore = Infinity
  for (let mask = 0; mask < 8; mask++) {
    const c = blank(version)
    drawPatterns(c, version)
    drawData(c, data)
    applyMask(c, mask)
    drawFormat(c, mask)
    const score = penalty(c)
    if (score < bestScore) {
      bestScore = score
      best = c
    }
  }

  const chosen = best!
  return { size: chosen.size, modules: chosen.modules }
}

/**
 * The symbol as one SVG path, quiet zone included.
 *
 * One path rather than a rectangle per module: version 4 is 33×33, and a
 * thousand DOM nodes on the projector tab is a thousand nodes the browser
 * re-lays-out every time the lobby re-renders.
 */
export function qrPath(matrix: QrMatrix): string {
  const parts: string[] = []
  for (let y = 0; y < matrix.size; y++) {
    for (let x = 0; x < matrix.size; x++) {
      if (matrix.modules[y][x]) parts.push(`M${x + QUIET} ${y + QUIET}h1v1h-1z`)
    }
  }
  return parts.join('')
}

/** Four modules of light on every side, as the standard requires to scan. */
export const QUIET = 4
