// GENERATED by tools/build-function.mjs — do not edit.
// Source: supabase/functions/_src/room.ts plus src/engine and src/game.
// Rebuild with `npm run build:function`.


// src/engine/types.ts
var ROLES = ["government", "business", "community", "activist"];
var TRUST_ROLES = ["government", "business", "activist"];
var SUPPORTIVE = /* @__PURE__ */ new Set([
  "SPEND_STEER",
  "TRANSITION",
  "PARTNER",
  "COLLABORATE"
]);
var DIRTY = /* @__PURE__ */ new Set(["EXPAND", "DEREGULATE"]);

// src/engine/content.ts
function loadContent(raw) {
  const pack = raw;
  if (!pack?.config || !Array.isArray(pack.scenarios)) {
    throw new Error("content pack: missing config or scenarios");
  }
  const scenarios = {};
  const roundVariants = {};
  for (const s of pack.scenarios) {
    scenarios[s.id] = s;
    (roundVariants[s.round] ??= []).push(s.id);
  }
  for (const ids of Object.values(roundVariants)) ids.sort();
  validate(pack, scenarios, roundVariants);
  return {
    config: pack.config,
    scenarios,
    roundVariants,
    resilienceFlags: new Set(pack.resilienceFlags),
    privateGoals: pack.privateGoals,
    insiderTips: pack.insiderTips
  };
}
function validate(pack, scenarios, roundVariants) {
  const problems = [];
  for (let r = 1; r <= 6; r++) {
    if (!roundVariants[r]?.length) problems.push(`round ${r} has no scenarios`);
  }
  for (const s of Object.values(scenarios)) {
    for (const role of ROLES) {
      const opts = s.options?.[role];
      if (!opts?.length) {
        problems.push(`${s.id}: role ${role} has no options`);
        continue;
      }
      for (const o of opts) {
        if (typeof o.e !== "number" || typeof o.g !== "number") {
          problems.push(`${o.id}: non-numeric effects`);
        }
        if (!o.headline) problems.push(`${o.id}: missing headline`);
      }
    }
  }
  const c = pack.config;
  for (const key of ["2", "3", "4"]) {
    if (!c.coalition?.[key]) problems.push(`config.coalition missing key ${key}`);
  }
  if (!c.driftTable?.length) problems.push("config.driftTable is empty");
  if (problems.length) {
    throw new Error(`content pack invalid:
  ${problems.join("\n  ")}`);
  }
}

// src/engine/engine.ts
function powInt(base, n) {
  let out = 1;
  for (let i = 0; i < n; i++) out *= base;
  return out;
}
function driftK(greenShare, content2) {
  for (const band of content2.config.driftTable) {
    if (greenShare <= band.greenShareMax) return band.k;
  }
  return content2.config.driftTable[content2.config.driftTable.length - 1].k;
}
function mac(emissions, content2) {
  const c = content2.config;
  return Math.max(
    c.mac_lo,
    Math.min(c.mac_lo + c.mac_span, c.mac_lo + c.mac_span * (emissions - c.mac_ref) / c.mac_range)
  );
}
function createGame(path, content2) {
  const s = content2.config.start;
  return {
    path: [...path],
    round: 0,
    emissions: s.e,
    growth: s.g,
    happiness: s.h,
    greenShare: s.gr,
    fiscal: s.fiscal,
    capital: s.capital,
    spotlights: s.spot,
    vetoes: content2.config.vetoes,
    trust: { government: 0, business: 0, activist: 0 },
    flags: /* @__PURE__ */ new Set(),
    gdpHistory: [],
    happinessHistory: [],
    picks: [],
    roleEmissions: { government: 0, business: 0, community: 0, activist: 0 },
    spotlightHits: 0,
    vetoesUsed: 0,
    coalitionRounds: 0,
    collabs: 0,
    selforg: 0,
    selfOrganiseSucceeded: 0,
    lastDirty: []
  };
}
function availableOptions(state, scenario, role, _content) {
  const out = [];
  for (const o of scenario.options[role]) {
    const cost = o.cost ?? {};
    const discount = state.flags.has("GRID_UPGRADED") && SUPPORTIVE.has(o.arch) ? 1 : 0;
    if (cost.fiscal !== void 0 && cost.fiscal > 0) {
      if (state.fiscal < Math.max(cost.fiscal - discount, 0)) continue;
    }
    if (cost.capital !== void 0 && cost.capital > 0) {
      if (state.capital < Math.max(cost.capital - discount, 0)) continue;
    }
    if (o.gate_trust && state.trust.government < o.gate_trust) continue;
    if (o.block_flag && state.flags.has(String(o.block_flag))) continue;
    out.push(o);
  }
  return out.length ? out : scenario.options[role].slice(0, 1);
}
function applyVeto(options) {
  const clean = options.filter((o) => !DIRTY.has(o.arch));
  return clean.length ? clean : options;
}
function countEvidence(flags) {
  let n = 0;
  for (const f of flags) if (f.startsWith("EVIDENCE")) n++;
  return n;
}
function playRound(state, input, content2) {
  const cfg = content2.config;
  const i = state.round;
  const scenario = content2.scenarios[state.path[i]];
  if (!scenario) throw new Error(`unknown scenario ${state.path[i]} for round ${i + 1}`);
  const rnd = i + 1;
  if (rnd >= 2) {
    state.fiscal += cfg.fiscal_income;
    if (state.growth >= cfg.fiscal_bonus_at) state.fiscal += 1;
    state.capital += 1;
    if (state.growth >= cfg.capital_income_at) state.capital += 1;
  }
  if (state.flags.has("SUBSIDY_LOCK") && (rnd === 4 || rnd === 5)) {
    state.fiscal = Math.max(0, state.fiscal - 1);
  }
  const sh = scenario.shock;
  let mult = 1;
  if (rnd === 5 && (state.flags.has("BUILT_COAL") || state.flags.has("REGULATORY_CAPTURE"))) {
    mult = 1.6;
  }
  if (rnd === 6) {
    if (state.emissions > cfg.r6_high_e) mult *= cfg.r6_high_mult;
    if (state.flags.has("BUILT_COAL")) mult *= 1.5;
    let nres = 0;
    for (const f of state.flags) if (content2.resilienceFlags.has(f)) nres++;
    mult *= Math.max(1 - Math.min(nres * cfg.r6_flag_reduce, cfg.r6_flag_cap), 0);
  }
  const shG = sh.g * mult;
  const shH = sh.h * mult;
  const shE = sh.e ?? 0;
  state.fiscal = Math.max(0, state.fiscal + (sh.fiscal ?? 0));
  state.capital = Math.max(0, state.capital + (sh.capital ?? 0));
  state.fiscal = Math.min(state.fiscal, cfg.fiscal_cap);
  state.capital = Math.min(state.capital, cfg.capital_cap);
  let vetoTarget = null;
  if (input.vetoTarget && state.vetoes > 0) {
    vetoTarget = input.vetoTarget;
    state.vetoes -= 1;
    state.vetoesUsed += 1;
  }
  const chosen = {};
  const vetoBlocked = [];
  for (const r of ROLES) {
    let opts = availableOptions(state, scenario, r, content2);
    if (r === vetoTarget) {
      const after = applyVeto(opts);
      for (const o of opts) if (!after.includes(o)) vetoBlocked.push(o.id);
      opts = after;
    }
    const pick2 = opts.find((o) => o.id === input.choices[r]);
    if (!pick2) {
      throw new Error(
        `${r} chose ${input.choices[r]}, which is not available this round (available: ${opts.map((o) => o.id).join(", ")})`
      );
    }
    chosen[r] = pick2;
  }
  const govRegulates = chosen.government.arch === "REGULATE";
  const govIsolated = chosen.government.arch === "DEREGULATE" && ROLES.filter((r) => r !== "government").every(
    (r) => !DIRTY.has(chosen[r].arch) && chosen[r].arch !== "DEMAND_RELIEF"
  );
  let spotTarget = null;
  if (chosen.activist.arch === "ESCALATE" && state.spotlights > 0) {
    const cand = ["business", "government"].filter((r) => DIRTY.has(chosen[r].arch));
    if (cand.length) {
      spotTarget = cand.reduce((a, b) => chosen[b].e > chosen[a].e ? b : a);
      state.spotlights -= 1;
    }
  }
  const macNow = mac(state.emissions, content2);
  let de = 0;
  let dg = 0;
  let dh = 0;
  let dgr = 0;
  const reveals = [];
  for (const r of ROLES) {
    const o = chosen[r];
    let m = 1;
    let partnerUnfunded = false;
    let selfOrganiseSupported = false;
    if (o.arch === "PARTNER") {
      const cofunded = (input.coFund ?? false) && state.fiscal >= 1;
      if (cofunded) {
        state.fiscal -= 1;
      } else {
        m *= cfg.partner_unfunded;
        partnerUnfunded = true;
      }
    }
    if (o.arch === "SELF_ORGANISE") {
      const supported = state.flags.has("MUTUAL_AID") || ["government", "business"].some((x) => SUPPORTIVE.has(chosen[x].arch));
      if (supported) {
        m *= cfg.self_org_mult;
        state.selfOrganiseSucceeded += 1;
        selfOrganiseSupported = true;
      }
    }
    if (o.arch === "REGULATE" && state.flags.has("REGULATORY_CAPTURE") && rnd >= 5) {
      m *= 0.5;
    }
    if (o.boost_flag && state.flags.has(o.boost_flag)) m *= 1.5;
    if (o.boost_evidence && countEvidence(state.flags) >= 2) m *= 2;
    if (r === "activist") m *= powInt(cfg.credibility_decay, state.collabs);
    if (r === "community" && o.arch === "SELF_ORGANISE") {
      m *= powInt(cfg.volunteer_fatigue, state.selforg);
    }
    if (r === "activist" && o.arch === "ESCALATE" && spotTarget) m *= 1.4;
    if (r === spotTarget) m *= cfg.spotlight_backdown;
    if (r === "business" && DIRTY.has(o.arch) && govRegulates) m *= cfg.regulation_bite;
    if (r === "government" && govIsolated) m *= cfg.public_pressure;
    const em = o.e < 0 ? cfg.e_green * macNow : cfg.e_dirty;
    const e = o.e * em * cfg.role_e[r];
    de += e * m;
    dg += o.g * m;
    dh += o.h * m * cfg.h_scale2;
    dgr += o.gr * m;
    state.roleEmissions[r] += e * m;
    const c = { ...o.cost ?? {} };
    if (state.flags.has("GRID_UPGRADED") && SUPPORTIVE.has(o.arch)) {
      for (const k2 of Object.keys(c)) {
        if (c[k2] > 0) c[k2] = Math.max(0, c[k2] - 1);
      }
    }
    state.fiscal = Math.max(0, state.fiscal - (c.fiscal ?? 0));
    state.capital = Math.max(0, state.capital - (c.capital ?? 0));
    if (o.grants) {
      const [, resource, amount] = o.grants;
      if (resource === "capital") state.capital += amount;
    }
    if (o.arch === "DEMAND_RELIEF") {
      if (state.fiscal >= 2) state.fiscal -= 1;
      else state.trust.government = Math.max(0, state.trust.government - 1);
    }
    const flagsSet = o.flags ?? [];
    for (const f of flagsSet) state.flags.add(f);
    if (o.arch === "COLLABORATE") state.collabs += 1;
    if (o.arch === "SELF_ORGANISE") state.selforg += 1;
    reveals.push({
      role: r,
      optionId: o.id,
      arch: o.arch,
      title: o.title,
      desc: o.desc,
      headline: o.headline,
      aligned: !DIRTY.has(o.arch) && o.arch !== "DEMAND_RELIEF",
      multiplier: m,
      emissions: e * m,
      partnerUnfunded,
      selfOrganiseSupported,
      spotlit: r === spotTarget,
      flagsSet: [...flagsSet]
    });
  }
  let aligned = 0;
  for (const r of ROLES) {
    if (!DIRTY.has(chosen[r].arch) && chosen[r].arch !== "DEMAND_RELIEF") aligned++;
  }
  const coalition = cfg.coalition[String(aligned)] ?? null;
  if (coalition) {
    de += coalition.emissions * cfg.coal_scale * macNow;
    dh += coalition.happiness * cfg.coal_scale;
    dgr += coalition.green * cfg.coal_scale;
    state.coalitionRounds += 1;
  }
  let forcedAbatement = 0;
  if (govRegulates) {
    forcedAbatement = cfg.regulate_abate * macNow * (DIRTY.has(chosen.business.arch) ? 1 : 0.45);
    de -= forcedAbatement;
    state.roleEmissions.government -= forcedAbatement;
    state.capital = Math.max(0, state.capital - 1);
  }
  if (govIsolated) {
    state.trust.government = Math.max(0, state.trust.government - 1);
  }
  if (spotTarget) {
    dh += cfg.accountability_bonus;
    state.trust[spotTarget] = Math.max(0, state.trust[spotTarget] - 1);
    state.spotlightHits += 1;
  }
  state.emissions += shE + de;
  const prevDev = state.growth - cfg.trend;
  state.growth = cfg.trend + cfg.persist * prevDev + shG + dg;
  state.growth = Math.max(-5, Math.min(9, state.growth));
  const hb = cfg.h_b0 + cfg.h_b_green * (state.greenShare / 100) + cfg.h_b_growth * (state.growth - 4.5);
  state.happiness = hb + cfg.h_persist * (state.happiness - hb) + shH + dh * cfg.h_scale;
  state.happiness = Math.max(0, Math.min(10, state.happiness));
  const nev = countEvidence(state.flags);
  let add = (dgr + nev * cfg.evidence_green) * cfg.green_scale;
  add *= Math.pow(1 - state.greenShare / 100, cfg.green_power);
  state.greenShare = Math.max(0, Math.min(100, state.greenShare * cfg.green_decay + add));
  state.growth += (state.greenShare - 10) / cfg.green_dividend;
  state.growth = Math.max(-5, Math.min(9, state.growth));
  const k = driftK(state.greenShare, content2);
  const drift = state.growth * k;
  state.emissions += drift;
  const awarded = {};
  for (const key of ["h", "gr"]) {
    let best = null;
    let bv = -99;
    for (const r of TRUST_ROLES) {
      const penalty = r === "business" && state.flags.has("LAYOFFS") ? 1 : 0;
      const v = chosen[r][key] - penalty;
      if (v > bv) {
        best = r;
        bv = v;
      }
    }
    if (best) {
      state.trust[best] += 1;
      if (key === "h") awarded.care = best;
      else awarded.future = best;
    }
  }
  state.lastDirty = ROLES.filter((r) => DIRTY.has(chosen[r].arch));
  state.gdpHistory.push(state.growth);
  state.happinessHistory.push(state.happiness);
  state.picks.push(Object.fromEntries(ROLES.map((r) => [r, chosen[r].id])));
  state.round += 1;
  return {
    round: rnd,
    scenarioId: scenario.id,
    shock: { g: shG, h: shH, e: shE },
    shockMultiplier: mult,
    vetoTarget,
    vetoBlocked,
    spotlightTarget: spotTarget,
    govRegulates,
    govIsolated,
    reveals,
    alignedCount: aligned,
    coalitionBonus: coalition,
    forcedAbatement,
    deltas: { e: shE + de, g: dg, h: dh, gr: dgr },
    trustAwarded: awarded,
    drift,
    driftK: k,
    state: publicState(state, content2)
  };
}
function averageGrowth(state) {
  if (!state.gdpHistory.length) return state.growth;
  return state.gdpHistory.reduce((a, b) => a + b, 0) / state.gdpHistory.length;
}
function projection2050(state, content2) {
  const remaining = Math.max(0, 6 - state.round);
  return state.emissions + remaining * state.growth * driftK(state.greenShare, content2);
}
function publicState(state, content2) {
  return {
    round: state.round,
    emissions: state.emissions,
    growth: state.growth,
    averageGrowth: averageGrowth(state),
    happiness: state.happiness,
    greenShare: state.greenShare,
    fiscal: state.fiscal,
    capital: state.capital,
    spotlights: state.spotlights,
    vetoes: state.vetoes,
    trust: { ...state.trust },
    flags: [...state.flags].sort(),
    projection2050: projection2050(state, content2)
  };
}
function result(state, content2) {
  const c = content2.config;
  const avgG = averageGrowth(state);
  const pe = state.emissions <= c.tgt_e;
  const pg = avgG >= c.tgt_g;
  const ph = state.happiness >= c.tgt_h;
  return {
    win: pe && pg && ph,
    pe,
    pg,
    ph,
    e: state.emissions,
    g: avgG,
    h: state.happiness,
    gr: state.greenShare,
    fiscal: state.fiscal,
    capital: state.capital,
    trust: { ...state.trust },
    flags: new Set(state.flags),
    roleEmissions: { ...state.roleEmissions },
    spotlightHits: state.spotlightHits,
    vetoesUsed: state.vetoesUsed,
    coalitionRounds: state.coalitionRounds,
    selfOrganiseSucceeded: state.selfOrganiseSucceeded,
    gdpHistory: [...state.gdpHistory],
    happinessHistory: [...state.happinessHistory],
    picks: state.picks.map((p) => ({ ...p }))
  };
}
function goalMet(goalId, res) {
  switch (goalId) {
    case "G-a":
      return res.trust.government >= 6;
    case "G-b":
      return Math.min(...res.gdpHistory) >= 4;
    case "G-c":
      return res.gr >= 55;
    case "B-a":
      return res.capital >= 6;
    case "B-b":
      return res.roleEmissions.business <= -40;
    case "B-c":
      return res.trust.business >= 2 && res.capital >= 4;
    case "C-a":
      return res.h >= 8;
    case "C-b":
      return Math.min(...res.happinessHistory) >= 6.3;
    case "C-c":
      return res.selfOrganiseSucceeded >= 4;
    case "A-a":
      return !res.flags.has("COMPROMISED") && res.e <= 175;
    case "A-b":
      return res.gr >= 52;
    case "A-c":
      return res.h >= 7 && res.spotlightHits >= 1;
    default:
      throw new Error(`unknown goal ${goalId}`);
  }
}

// src/game/hints.ts
function variant(id, n) {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = h * 31 + id.charCodeAt(i) >>> 0;
  return h % n;
}
var BY_ARCHETYPE = {
  SPEND_STEER: (s) => [
    s.unpopular ? "Expensive. Right. Not everyone will agree." : "Expensive, and the country will feel it working.",
    "Bold. Needs the public behind you.",
    s.builds ? "Buys a green economy. Empties the Treasury." : "Public money, pointed in one direction."
  ],
  REGULATE: (s) => [
    "Makes the polluter move. Costs you friends.",
    s.slowsEconomy ? "It works. Growth will not thank you." : "Force beats persuasion. Someone pays.",
    "The law does what the meeting could not."
  ],
  DEREGULATE: (s) => [
    s.popular ? "Popular today. Expensive by Round 6." : "Cheap now. The bill arrives later.",
    "Protects growth. Costs the country carbon.",
    s.legacy ? "Easy. And it closes doors you will want." : "Do nothing, and hope. It has worked before."
  ],
  TRANSITION: (s) => [
    "Real money, real pain, real cuts.",
    s.slowsEconomy ? "Hurts this year. Pays for a decade." : "The expensive answer, and the honest one.",
    s.builds ? "The biggest green move on the table." : "Capex now. Certainty later."
  ],
  EXPAND: (s) => [
    s.popular ? "Profitable. The room will notice." : "Good for the balance sheet. Bad for the air.",
    "Faster, cheaper, dirtier. Everyone sees it.",
    "Business as usual, at speed."
  ],
  PARTNER: () => [
    "Halves in value unless someone co-funds it.",
    "Only works if the Government pays its half.",
    "A deal. It needs a partner to be worth anything."
  ],
  ADAPT: (s) => [
    "Quiet, cheap, and it costs you something.",
    s.unpopular ? "Absorb it. Nobody enjoys this one." : "Get on with it. No drama, small gains.",
    "The unglamorous option that usually helps."
  ],
  DEMAND_RELIEF: () => [
    "Makes the Government pay, one way or another.",
    "Relief now. It comes out of someone else.",
    "Loud, popular, and it breaks the coalition."
  ],
  SELF_ORGANISE: () => [
    "Doubles if the powerful actually back you.",
    "Do it yourselves. Better with real support.",
    "Community power. It tires people out."
  ],
  ESCALATE: () => [
    "Loud. Effective. Nobody here will thank you.",
    "Pressure works. It also makes enemies.",
    "Name them. Watch the room change."
  ],
  COLLABORATE: () => [
    "Real influence, and a little of your soul.",
    "A seat at the table costs you credibility.",
    "Inside the room. Quieter every time."
  ],
  EDUCATE: (s) => [
    s.slowBurn ? "Nothing today. Something big by Round 6." : "Slow, cheap, and it compounds.",
    "Evidence now. It pays every round after.",
    "The patient move. It always adds up."
  ]
};
var MAX = 52;
function optionHint(option) {
  const authored = option.hint;
  if (authored) return authored.slice(0, MAX);
  const flags = option.flags ?? [];
  const shape = {
    cuts: option.e < 0,
    slowsEconomy: option.g < 0,
    unpopular: option.h < 0,
    popular: option.h >= 0.5,
    builds: option.gr >= 8,
    legacy: flags.length > 0,
    slowBurn: flags.some((f) => f.startsWith("EVIDENCE"))
  };
  const build = BY_ARCHETYPE[option.arch];
  if (!build) return "A judgement call. Make it.";
  const choices = build(shape).filter((s) => s.length <= MAX);
  if (!choices.length) return "A judgement call. Make it.";
  return choices[variant(option.id, choices.length)];
}
function costLabel(option) {
  const c = option.cost ?? {};
  const parts = [];
  if (c.fiscal) parts.push(c.fiscal > 0 ? `${c.fiscal} FP` : `+${-c.fiscal} FP`);
  if (c.capital) parts.push(c.capital > 0 ? `${c.capital} C` : `+${-c.capital} C`);
  return parts.length ? parts.join(" \xB7 ") : "FREE";
}

// src/game/copy.ts
var PRIVATE_LINE = {
  financial: {
    government: "The Treasury wants a decision today. Your backbenchers want a different one.",
    business: "The board meets in an hour. They want to know what this costs.",
    community: "Three people on your street lost their jobs before lunch.",
    activist: "Every rescue package is a chance to attach a condition. Or to be ignored."
  },
  energy: {
    government: "The subsidy bill is now the largest line in your budget. Everybody knows it.",
    business: "Your energy costs just became your biggest risk, and your biggest opportunity.",
    community: "The bill arrived this morning. People are talking about nothing else.",
    activist: "This is the round where the country picks its next thirty years of power."
  },
  health: {
    government: "Hospitals are calling your office directly. So are the employers.",
    business: "Your workforce is the exposure here, not your plant.",
    community: "People are frightened, and they are looking to each other, not upward.",
    activist: "Clean air just stopped being an abstraction. Use it or lose the moment."
  },
  election: {
    government: "Everything you chose in the last three rounds is now a poster or a scandal.",
    business: "Whoever wins writes the rules you operate under. Money talks, and it is recorded.",
    community: "You are the only one in this room who actually casts a vote.",
    activist: "Endorsement is the only currency you have. Spend it once, spend it well."
  },
  pollution: {
    government: "Somebody will be blamed. You get to decide whether it is a company or a law.",
    business: "Your permit may be lawful. That is not the same as being defensible.",
    community: "This happened to your neighbourhood, not to a statistic.",
    activist: "The evidence exists. The question is whether anyone has to look at it."
  },
  disaster: {
    government: "This is the last round. Whatever you do now is what you are remembered for.",
    business: "The rebuild is a contract. It is also the last chance to be on the right side.",
    community: "Your people are in the water and the boats are mostly volunteers.",
    activist: "Ten years of work, and one afternoon to decide what it was for."
  }
};
function privateLine(type, role) {
  return PRIVATE_LINE[type]?.[role] ?? "The room is waiting for you.";
}
var DEMAND_PHRASES = [
  { id: "pay-first", text: (t) => `the ${t} pays its share before anyone else moves` },
  { id: "no-dirty", text: (t) => `the ${t} does not take the cheap option this round` },
  { id: "go-public", text: (t) => `the ${t} says out loud what it is about to choose` },
  { id: "co-fund", text: (t) => `the ${t} co-funds the partnership on the table` },
  { id: "protect-jobs", text: (t) => `the ${t} guarantees nobody loses a job over this` },
  { id: "no-more-delay", text: (t) => `the ${t} stops asking everyone else to go first` }
];
var BOARD_NAME = {
  government: "The Government",
  business: "The Business",
  community: "The Community",
  activist: "The Activist"
};
function asPledgeObject(title) {
  return title.split(" ").map((w) => /^(RG|EV|ID|PPA|GW|[A-Z]{2,})$/.test(w) ? w : w.toLowerCase()).join(" ");
}

// src/game/rng.ts
function mulberry32(seed) {
  let a = seed >>> 0;
  return function next() {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function draw(seed, cursor) {
  const rand = mulberry32(seed + cursor * 2654435769);
  return { value: rand(), cursor: cursor + 1 };
}
function pick(items, seed, cursor) {
  const d = draw(seed, cursor);
  return { value: items[Math.floor(d.value * items.length)], cursor: d.cursor };
}
function roomCode(seed) {
  const letters = "ABCDEFGHJKLMNPQRSTUVWXYZ";
  let c = 0;
  let out = "";
  for (let i = 0; i < 4; i++) {
    const d = draw(seed, c);
    c = d.cursor;
    out += letters[Math.floor(d.value * letters.length)];
  }
  return out;
}

// src/game/session.ts
var PHASE_MS = {
  lobby: 0,
  // ends when the facilitator starts
  briefing: 2e4,
  crisis: 3e4,
  table: 9e4,
  choice: 45e3,
  reckoning: 75e3,
  summary: 8e3,
  results: 0,
  // advances on facilitator input
  ended: 0
};
var ROLE_LABEL = {
  government: "Government",
  business: "Business",
  community: "Community",
  activist: "Activist"
};
var ROLE_RESOURCE = {
  government: { kind: "fiscal", label: "Your Fiscal Points" },
  business: { kind: "capital", label: "Your Capital" },
  community: { kind: "trust-awards", label: "Public Mandate vetoes" },
  activist: { kind: "spotlights", label: "Spotlights" }
};

// src/game/room.ts
function createRoom(content2, seed, now) {
  let cursor = 0;
  const path = [];
  for (let r = 1; r <= 6; r++) {
    const p = pick(content2.roundVariants[r], seed, cursor);
    cursor = p.cursor;
    path.push(p.value);
  }
  const players = Object.fromEntries(
    ROLES.map((role) => [
      role,
      {
        role,
        name: "",
        connected: false,
        goalId: null,
        choiceId: null,
        locked: false,
        autoLocked: false,
        defaulted: false,
        lockedAt: null
      }
    ])
  );
  return {
    code: roomCode(seed),
    createdAt: now,
    phase: "lobby",
    phaseEndsAt: null,
    pausedAt: null,
    players,
    game: createGame(path, content2),
    promises: [],
    offers: [],
    tips: [],
    vetoTarget: null,
    coFund: false,
    spotlightCalled: false,
    lastRound: null,
    history: [],
    tipRotation: [],
    seed,
    rngCursor: cursor
  };
}
function currentScenario(room, content2) {
  const id = room.game.path[room.game.round];
  return id ? content2.scenarios[id] ?? null : null;
}
function roundNumber(room) {
  return Math.min(room.game.round + 1, 6);
}
function displayRound(room) {
  if ((room.phase === "reckoning" || room.phase === "summary") && room.lastRound) {
    return room.lastRound.round;
  }
  return roundNumber(room);
}
function setPhase(room, phase, now) {
  room.phase = phase;
  const ms = PHASE_MS[phase];
  room.phaseEndsAt = ms > 0 ? now + ms : null;
}
function isPaused(room) {
  return room.pausedAt != null;
}
function clockNow(room, now) {
  return room.pausedAt ?? now;
}
function everyoneLocked(room) {
  const held = ROLES.filter((r) => room.players[r].name);
  if (!held.length) return false;
  return held.every((r) => room.players[r].locked);
}
function vetoesRemaining(room) {
  return Math.max(0, room.game.vetoes - (room.vetoTarget ? 1 : 0));
}
function spotlightsRemaining(room) {
  return Math.max(0, room.game.spotlights - (room.spotlightCalled ? 1 : 0));
}
function canReceive(role) {
  const kind = ROLE_RESOURCE[role].kind;
  return kind === "fiscal" || kind === "capital";
}
function choosableOptions(room, content2, role) {
  const scenario = currentScenario(room, content2);
  if (!scenario) return [];
  const opts = availableOptions(room.game, scenario, role, content2);
  return role === room.vetoTarget ? applyVeto(opts) : opts;
}
function authorise(seat, cmd) {
  if (seat === "dashboard") {
    return cmd.t === "start" || cmd.t === "advance" || cmd.t === "pause" || cmd.t === "resume" ? cmd : null;
  }
  switch (cmd.t) {
    case "join":
    case "reconnect":
    case "leave":
    case "pickGoal":
    case "promise":
    case "demand":
    case "respondOffer":
    case "spotlight":
    case "veto":
    case "coFund":
    case "publishTip":
    case "choose":
    case "lock":
      return { ...cmd, role: seat };
    case "offer":
      return { ...cmd, from: seat };
    default:
      return null;
  }
}
var FROZEN_WHILE_PAUSED = /* @__PURE__ */ new Set([
  "promise",
  "demand",
  "offer",
  "respondOffer",
  "spotlight",
  "veto",
  "coFund",
  "publishTip",
  "choose",
  "lock"
]);
function apply(room, cmd, content2, now) {
  if (isPaused(room) && FROZEN_WHILE_PAUSED.has(cmd.t)) return room;
  const at = clockNow(room, now);
  switch (cmd.t) {
    case "join": {
      const p = room.players[cmd.role];
      if (p.name && p.name !== cmd.name) return room;
      p.name = cmd.name;
      p.connected = true;
      return room;
    }
    case "reconnect":
      room.players[cmd.role].connected = true;
      return room;
    /**
     * Leaving empties the chair rather than dimming it.
     *
     * A seat that stays named for the rest of the workshop is unrecoverable
     * without a new room, so the one thing `leave` must do is make the seat
     * takeable again — by somebody else, or by the same person on a new phone.
     * A sealed goal belongs to the person, not the chair, so it goes with them.
     */
    case "leave": {
      const p = room.players[cmd.role];
      p.name = "";
      p.connected = false;
      p.goalId = null;
      p.choiceId = null;
      p.locked = false;
      p.autoLocked = false;
      p.defaulted = false;
      p.lockedAt = null;
      return room;
    }
    case "pickGoal": {
      if (room.players[cmd.role].goalId) return room;
      room.players[cmd.role].goalId = cmd.goalId;
      return room;
    }
    case "start": {
      if (room.phase !== "lobby") return room;
      setPhase(room, "briefing", at);
      return room;
    }
    case "advance":
      return advance(room, content2, at);
    /**
     * Stop the clock, wherever the room has got to.
     *
     * The one control a facilitator asks for by the second session: a fire
     * alarm, a latecomer, a question worth answering properly, or a table that
     * has just started arguing well and should not be cut off by a countdown.
     */
    case "pause": {
      if (isPaused(room)) return room;
      room.pausedAt = now;
      return room;
    }
    /**
     * Start it again, giving back exactly what was left.
     *
     * The deadline moves forward by the length of the pause rather than being
     * recomputed, so a table stopped with nine seconds of THE CHOICE remaining
     * restarts with nine seconds — not with a fresh forty-five, and not with
     * the phase already over.
     */
    case "resume": {
      if (!isPaused(room)) return room;
      if (room.phaseEndsAt !== null) room.phaseEndsAt += now - room.pausedAt;
      room.pausedAt = null;
      return room;
    }
    case "promise": {
      if (room.phase !== "table") return room;
      const scenario = currentScenario(room, content2);
      const option = scenario?.options[cmd.role].find((o) => o.id === cmd.optionId);
      if (!option) return room;
      room.promises = room.promises.filter(
        (p) => !(p.round === roundNumber(room) && p.from === cmd.role && p.kind === "promise")
      );
      room.promises.push({
        id: `${cmd.role}-${roundNumber(room)}-p`,
        round: roundNumber(room),
        from: cmd.role,
        kind: "promise",
        text: `${BOARD_NAME[cmd.role]} will ${asPledgeObject(option.title)}.`,
        optionId: option.id,
        outcome: "unresolved"
      });
      return room;
    }
    case "demand": {
      if (room.phase !== "table") return room;
      const phrase = DEMAND_PHRASES.find((p) => p.id === cmd.phraseId);
      if (!phrase) return room;
      room.promises = room.promises.filter(
        (p) => !(p.round === roundNumber(room) && p.from === cmd.role && p.kind === "demand")
      );
      room.promises.push({
        id: `${cmd.role}-${roundNumber(room)}-d`,
        round: roundNumber(room),
        from: cmd.role,
        kind: "demand",
        text: `${BOARD_NAME[cmd.role]} demands ${phrase.text(ROLE_LABEL[cmd.target])}.`,
        optionId: null,
        outcome: "unresolved"
      });
      return room;
    }
    case "offer": {
      if (room.phase !== "table") return room;
      if (!canReceive(cmd.from) || !canReceive(cmd.to) || cmd.from === cmd.to) return room;
      const held = cmd.resource === "fiscal" ? room.game.fiscal : room.game.capital;
      if (cmd.amount < 1 || cmd.amount > held) return room;
      room.offers.push({
        id: `o${room.offers.length}-${roundNumber(room)}`,
        round: roundNumber(room),
        from: cmd.from,
        to: cmd.to,
        resource: cmd.resource,
        amount: cmd.amount,
        status: "pending"
      });
      return room;
    }
    case "respondOffer": {
      const offer = room.offers.find((o) => o.id === cmd.offerId && o.to === cmd.role);
      if (!offer || offer.status !== "pending") return room;
      if (!cmd.accept) {
        offer.status = "declined";
        return room;
      }
      offer.status = "accepted";
      const toResource = ROLE_RESOURCE[offer.to].kind;
      const fromResource = ROLE_RESOURCE[offer.from].kind;
      if (fromResource === "fiscal" && toResource === "capital") {
        const moved = Math.min(offer.amount, room.game.fiscal);
        room.game.fiscal -= moved;
        room.game.capital += moved;
      } else if (fromResource === "capital" && toResource === "fiscal") {
        const moved = Math.min(offer.amount, room.game.capital);
        room.game.capital -= moved;
        room.game.fiscal += moved;
      }
      return room;
    }
    case "spotlight": {
      if (room.phase !== "table" || cmd.role !== "activist") return room;
      if (room.game.spotlights <= 0) return room;
      room.spotlightCalled = true;
      return room;
    }
    case "veto": {
      if (room.phase !== "table" || cmd.role !== "community") return room;
      if (room.game.vetoes <= 0 || room.vetoTarget) return room;
      room.vetoTarget = cmd.target;
      const removed = choosableOptions(room, content2, cmd.target).map((o) => o.id);
      const p = room.players[cmd.target];
      if (p.choiceId && !removed.includes(p.choiceId)) {
        p.choiceId = null;
        p.locked = false;
        p.lockedAt = null;
      }
      return room;
    }
    case "coFund": {
      if (cmd.role !== "government") return room;
      room.coFund = cmd.agree;
      return room;
    }
    case "publishTip": {
      const tip = room.tips.find((t) => t.round === roundNumber(room) && t.to === cmd.role);
      if (!tip || tip.published) return room;
      tip.published = true;
      return room;
    }
    /**
     * Selecting a card. Not committing to it.
     *
     * Tapping to read a card more closely must never be the same act as
     * spending the round on it, so this only moves the selection — `lock` is
     * the irreversible half, and until it lands a player may change their mind
     * as often as they like.
     */
    case "choose": {
      if (room.phase !== "choice" && room.phase !== "table") return room;
      const p = room.players[cmd.role];
      if (p.locked) return room;
      const allowed = choosableOptions(room, content2, cmd.role);
      if (!allowed.some((o) => o.id === cmd.optionId)) return room;
      p.choiceId = cmd.optionId;
      return room;
    }
    /** Committing. From here the choice screen is a record, not a decision. */
    case "lock": {
      if (room.phase !== "choice") return room;
      const p = room.players[cmd.role];
      if (p.locked || p.choiceId === null) return room;
      const allowed = choosableOptions(room, content2, cmd.role);
      if (!allowed.some((o) => o.id === p.choiceId)) return room;
      p.locked = true;
      p.autoLocked = false;
      p.defaulted = false;
      p.lockedAt = at;
      if (everyoneLocked(room)) return resolveRound(room, content2, at);
      return room;
    }
    default:
      return room;
  }
}
function tick(room, content2, now) {
  if (isPaused(room)) return room;
  if (room.phaseEndsAt === null || now < room.phaseEndsAt) return room;
  return advance(room, content2, now);
}
function advance(room, content2, now) {
  switch (room.phase) {
    case "lobby":
      setPhase(room, "briefing", now);
      return room;
    case "briefing":
      return openRound(room, content2, now);
    case "crisis":
      setPhase(room, "table", now);
      return room;
    case "table":
      setPhase(room, "choice", now);
      return room;
    case "choice":
      return resolveRound(room, content2, now);
    case "reckoning":
      setPhase(room, "summary", now);
      return room;
    case "summary":
      if (room.game.round >= 6) {
        setPhase(room, "results", now);
        return room;
      }
      return openRound(room, content2, now);
    case "results":
      setPhase(room, "ended", now);
      return room;
    default:
      return room;
  }
}
function openRound(room, content2, now) {
  room.vetoTarget = null;
  room.coFund = false;
  room.spotlightCalled = false;
  for (const role of ROLES) {
    room.players[role].choiceId = null;
    room.players[role].locked = false;
    room.players[role].autoLocked = false;
    room.players[role].defaulted = false;
    room.players[role].lockedAt = null;
  }
  dealTip(room, content2);
  setPhase(room, "crisis", now);
  return room;
}
function resolveRound(room, content2, now) {
  for (const role of ROLES) {
    const p = room.players[role];
    if (p.locked) continue;
    if (p.choiceId === null) {
      const opts = choosableOptions(room, content2, role);
      if (!opts.length) continue;
      p.choiceId = opts[0].id;
      p.defaulted = true;
    }
    p.locked = true;
    p.autoLocked = true;
    p.lockedAt = now;
  }
  const choices = Object.fromEntries(
    ROLES.map((r) => [r, room.players[r].choiceId])
  );
  if (!room.spotlightCalled) {
    const activistOption = content2.scenarios[room.game.path[room.game.round]].options.activist.find(
      (o) => o.id === choices.activist
    );
    if (activistOption?.arch === "ESCALATE") {
      const held = room.game.spotlights;
      room.game.spotlights = 0;
      const log2 = playRound(room.game, { choices, vetoTarget: room.vetoTarget, coFund: room.coFund }, content2);
      room.game.spotlights = held;
      return finishRound(room, log2, choices, content2, now);
    }
  }
  const log = playRound(room.game, { choices, vetoTarget: room.vetoTarget, coFund: room.coFund }, content2);
  return finishRound(room, log, choices, content2, now);
}
function finishRound(room, log, choices, content2, now) {
  for (const p of room.promises) {
    if (p.round !== log.round || p.kind !== "promise" || !p.optionId) continue;
    p.outcome = choices[p.from] === p.optionId ? "kept" : "broken";
  }
  const tip = room.tips.find((t) => t.round === log.round);
  if (tip?.published) {
    tip.revealed = true;
    applyTipStake(room, tip);
  }
  for (const o of room.offers) {
    if (o.round === log.round && o.status === "pending") o.status = "expired";
  }
  room.lastRound = log;
  room.history.push(log);
  void content2;
  setPhase(room, "reckoning", now);
  return room;
}
function applyTipStake(room, tip) {
  if (tip.to === "community") {
    room.game.vetoes = tip.isTrue ? Math.min(3, room.game.vetoes + 1) : Math.max(0, room.game.vetoes - 1);
    return;
  }
  const role = tip.to;
  room.game.trust[role] = tip.isTrue ? room.game.trust[role] + 1 : Math.max(0, room.game.trust[role] - 1);
}
function dealTip(room, content2) {
  const round = roundNumber(room);
  if (room.tips.some((t) => t.round === round)) return;
  let cursor = room.rngCursor;
  let candidates = ROLES.filter((r) => !room.tipRotation.includes(r));
  if (!candidates.length) {
    const last = room.tipRotation[room.tipRotation.length - 1];
    candidates = ROLES.filter((r) => r !== last);
  } else if (room.tipRotation.length) {
    const last = room.tipRotation[room.tipRotation.length - 1];
    const withoutLast = candidates.filter((r) => r !== last);
    if (withoutLast.length) candidates = withoutLast;
  }
  const chosen = pick(candidates, room.seed, cursor);
  cursor = chosen.cursor;
  const to = chosen.value;
  const built = buildTip(room, content2, to, round, cursor);
  cursor = built.cursor;
  room.tips.push(built.tip);
  room.tipRotation.push(to);
  room.rngCursor = cursor;
}
function buildTip(room, content2, to, round, cursorIn) {
  let cursor = cursorIn;
  const tips = content2.insiderTips;
  const scenarioId = room.game.path[room.game.round];
  const nextScenarioId = room.game.path[room.game.round + 1];
  const roll = draw(room.seed, cursor);
  cursor = roll.cursor;
  const wantRumour = roll.value < 0.25 && round >= 2;
  const kinds = [];
  if (!wantRumour) {
    if (nextScenarioId) kinds.push("forecast");
    kinds.push("intel");
    if (round >= 2) kinds.push("dossier");
  }
  if (wantRumour || !kinds.length) kinds.push("rumour");
  const kindPick = pick(kinds, room.seed, cursor);
  cursor = kindPick.cursor;
  const kind = kindPick.value;
  if (kind === "rumour") {
    const whisperIds = Object.keys(tips.whispers);
    const w = pick(whisperIds, room.seed, cursor);
    cursor = w.cursor;
    const truth = draw(room.seed, cursor);
    cursor = truth.cursor;
    return {
      tip: {
        id: `tip-${round}`,
        round,
        to,
        kind: "rumour",
        reliability: "UNVERIFIED",
        source: "A rumour going round",
        text: tips.whispers[w.value],
        isTrue: truth.value < tips.whisperAccuracy,
        published: false,
        revealed: false
      },
      cursor
    };
  }
  if (kind === "forecast" && nextScenarioId) {
    const nextType = content2.scenarios[nextScenarioId].type;
    const lines = tips.forecasts[nextType] ?? [];
    const line = lines.length ? pick(lines, room.seed, cursor) : { value: "", cursor };
    cursor = line.cursor;
    return {
      tip: {
        id: `tip-${round}`,
        round,
        to,
        kind: "forecast",
        reliability: "CONFIRMED",
        source: "Cabinet Situation Room",
        text: line.value || "Something is coming. Nobody will say what.",
        isTrue: true,
        published: false,
        revealed: false
      },
      cursor
    };
  }
  if (kind === "dossier") {
    const others = ROLES.filter((r) => r !== to && room.players[r].goalId);
    if (others.length) {
      const target = pick(others, room.seed, cursor);
      cursor = target.cursor;
      const goalId = room.players[target.value].goalId;
      return {
        tip: {
          id: `tip-${round}`,
          round,
          to,
          kind: "dossier",
          reliability: "CONFIRMED",
          source: "A friend in the ministry",
          text: tips.whispers[goalId] ?? "They want something they have not said out loud.",
          isTrue: true,
          published: false,
          revealed: false
        },
        cursor
      };
    }
  }
  return {
    tip: {
      id: `tip-${round}`,
      round,
      to,
      kind: "memo",
      reliability: "CONFIRMED",
      source: "A sealed brief",
      text: tips.intel[scenarioId] ?? "The official figures are not the real ones.",
      isTrue: true,
      published: false,
      revealed: false
    },
    cursor
  };
}
function dashboardView(room, content2) {
  const scenario = currentScenario(room, content2);
  const held = ROLES.filter((r) => room.players[r].name);
  const waiting = held.filter((r) => !room.players[r].locked);
  const lastLock = held.length > 1 && waiting.length === 1 ? waiting[0] : null;
  const tip = room.tips.find((t) => t.round === displayRound(room));
  const published = tip?.published && tip ? {
    from: tip.to,
    text: tip.text,
    source: tip.source,
    verdict: tip.revealed ? tip.isTrue ? "true" : "false" : null
  } : null;
  const veto = room.vetoTarget ? {
    target: room.vetoTarget,
    removed: scenario ? availableOptions(room.game, scenario, room.vetoTarget, content2).filter((o) => DIRTY.has(o.arch)).map((o) => o.title) : [],
    remaining: vetoesRemaining(room)
  } : null;
  return {
    code: room.code,
    phase: room.phase,
    phaseEndsAt: room.phaseEndsAt,
    paused: isPaused(room),
    pausedAt: room.pausedAt ?? null,
    round: displayRound(room),
    scenario: scenario ? { id: scenario.id, title: scenario.title, type: scenario.type, situation: scenario.situation } : null,
    state: publicState(room.game, content2),
    seats: ROLES.map((role) => ({
      role,
      name: room.players[role].name || null,
      connected: room.players[role].connected,
      locked: room.players[role].locked,
      lastToLock: lastLock === role
    })),
    promises: room.promises.filter((p) => p.round === displayRound(room)),
    offersInFlight: room.offers.filter((o) => o.round === displayRound(room) && o.status === "pending"),
    tipDealtThisRound: Boolean(tip),
    publishedTip: published,
    spotlight: room.spotlightCalled ? {
      by: "activist",
      // Whoever takes the dirtiest option this round wears it. Nobody
      // knows who that is until the choices lock, so do not pretend to.
      target: room.lastRound?.spotlightTarget ?? null,
      remaining: spotlightsRemaining(room)
    } : null,
    veto,
    lastRound: room.lastRound,
    history: room.history,
    headlines: room.history.flatMap((h) => h.reveals.map((r) => r.headline)).slice(-12),
    targets: {
      emissions: content2.config.tgt_e,
      growth: content2.config.tgt_g,
      happiness: content2.config.tgt_h
    }
  };
}
function phoneView(room, content2, role) {
  const scenario = currentScenario(room, content2);
  const player = room.players[role];
  const showOptions = room.phase === "table" || room.phase === "choice";
  let options = [];
  if (scenario && showOptions) {
    const affordableAndOpen = availableOptions(room.game, scenario, role, content2);
    const afterVeto = role === room.vetoTarget ? applyVeto(affordableAndOpen) : affordableAndOpen;
    options = scenario.options[role].map((o) => {
      const open = affordableAndOpen.some((a) => a.id === o.id);
      const choosable = afterVeto.some((a) => a.id === o.id);
      let disabled = null;
      let note = null;
      if (!open) {
        if (o.gate_trust && room.game.trust.government < o.gate_trust) {
          disabled = "gate";
          note = `Needs ${o.gate_trust} Trust. The country has not backed you.`;
        } else if (o.block_flag && room.game.flags.has(String(o.block_flag))) {
          disabled = "gate";
          note = "A promise you made earlier closed this door.";
        } else {
          disabled = "afford";
          const need = o.cost?.fiscal ?? o.cost?.capital ?? 0;
          const have = o.cost?.fiscal ? room.game.fiscal : room.game.capital;
          note = `You have ${have} of ${need}.`;
        }
      } else if (!choosable) {
        disabled = "veto";
        note = '"The public will simply not accept this." \u2014 the Community, this round only';
      }
      return {
        id: o.id,
        title: o.title,
        desc: o.desc,
        cost: costLabel(o),
        hint: optionHint(o),
        available: choosable,
        disabled,
        disabledNote: note
      };
    });
  }
  const resourceKind = ROLE_RESOURCE[role].kind;
  const resourceValue = resourceKind === "fiscal" ? room.game.fiscal : resourceKind === "capital" ? room.game.capital : resourceKind === "spotlights" ? room.game.spotlights : vetoesRemaining(room);
  const goalChoices = player.goalId === null ? content2.privateGoals[role].map((g) => ({ id: g.id, title: g.title, desc: g.desc })) : null;
  const ownGoal = player.goalId ? content2.privateGoals[role].find((g) => g.id === player.goalId) ?? null : null;
  const narrating = room.phase === "reckoning" || room.phase === "summary";
  return {
    code: room.code,
    role,
    name: player.name,
    phase: room.phase,
    phaseEndsAt: room.phaseEndsAt,
    paused: isPaused(room),
    pausedAt: room.pausedAt ?? null,
    round: displayRound(room),
    scenario: scenario && !narrating ? { id: scenario.id, title: scenario.title, situation: scenario.situation, type: scenario.type } : null,
    privateLine: scenario && !narrating ? privateLine(scenario.type, role) : null,
    options,
    choiceId: player.choiceId,
    locked: player.locked,
    resource: { kind: resourceKind, value: resourceValue, label: ROLE_RESOURCE[role].label },
    trust: { ...room.game.trust },
    vetoesRemaining: vetoesRemaining(room),
    spotlightsRemaining: spotlightsRemaining(room),
    spotlightCalled: room.spotlightCalled,
    coFund: room.coFund,
    goalId: player.goalId,
    goalTitle: ownGoal?.title ?? null,
    goalDesc: ownGoal?.desc ?? null,
    goalChoices,
    // Only ever your own tip, and only while it is yours to act on.
    tip: room.tips.find((t) => t.to === role && t.round === displayRound(room)) ?? null,
    promises: room.promises.filter((p) => p.round === displayRound(room)),
    incomingOffers: room.offers.filter((o) => o.to === role && o.status === "pending"),
    sentOffers: room.offers.filter((o) => o.from === role && o.round === displayRound(room)),
    seats: ROLES.map((r) => ({
      role: r,
      name: room.players[r].name || null,
      connected: room.players[r].connected,
      locked: room.players[r].locked
    })),
    roundResult: roundResultCopy(room, role),
    waitingOn: ROLES.filter((r) => room.players[r].name && !room.players[r].locked).length
  };
}
function roundResultCopy(room, role) {
  const log = room.lastRound;
  if (!log || room.phase !== "reckoning" && room.phase !== "summary") return null;
  const mine = log.reveals.find((r) => r.role === role);
  if (!mine) return null;
  const player = room.players[role];
  const didWhat = player.defaulted ? `You ran out of time. The clock picked \u201C${mine.title}\u201D.` : player.autoLocked ? `You had \u201C${mine.title}\u201D selected, and the clock locked it in.` : `You chose \u201C${mine.title}\u201D.`;
  const costBits = [];
  if (mine.partnerUnfunded) costBits.push("Nobody co-funded it, so it landed at half strength.");
  if (mine.spotlit) costBits.push("You were named publicly, and it cost you.");
  if (mine.selfOrganiseSupported) costBits.push("Real backing arrived, and it counted double.");
  if (log.govIsolated && role === "government") {
    costBits.push("You moved alone, and the country only half-followed.");
  }
  if (!costBits.length) costBits.push("It landed as you intended.");
  const others = [];
  if (log.alignedCount >= 3) {
    others.push(
      log.alignedCount === 4 ? "All four of you moved together \u2014 the coalition held." : "Three of you moved together \u2014 the coalition held."
    );
  } else {
    others.push("The table did not move together this round.");
  }
  const broken = room.promises.filter((p) => p.round === log.round && p.outcome === "broken");
  if (broken.length) others.push(`${broken.map((b) => b.from).join(" and ")} broke a promise.`);
  return { didWhat, cost: costBits.join(" "), others: others.join(" ") };
}
function endgame(room, content2) {
  const res = result(room.game, content2);
  const c = content2.config;
  return {
    win: res.win,
    targets: [
      { key: "emissions", value: res.e, target: c.tgt_e, met: res.pe },
      { key: "growth", value: res.g, target: c.tgt_g, met: res.pg },
      { key: "happiness", value: res.h, target: c.tgt_h, met: res.ph }
    ],
    players: ROLES.map((role) => {
      const player = room.players[role];
      const goal = content2.privateGoals[role].find((g) => g.id === player.goalId) ?? null;
      const met = player.goalId ? goalMet(player.goalId, res) : false;
      return {
        role,
        name: player.name,
        goalId: player.goalId,
        goalTitle: goal?.title ?? null,
        goalMet: met,
        title: res.win ? "NATION BUILDER" : met ? "HOLLOW VICTORY" : "NO TITLE"
      };
    })
  };
}

// supabase/functions/_src/room.ts
import { PACK } from "./content.gen.ts";
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var content = loadContent(PACK);
var CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS"
};
var json = (body, status = 200) => new Response(JSON.stringify(body), {
  status,
  headers: { ...CORS, "Content-Type": "application/json" }
});
async function rest(path, init = {}) {
  return fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    ...init,
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      ...init.headers ?? {}
    }
  });
}
function serialise(room) {
  return { ...room, game: { ...room.game, flags: [...room.game.flags] } };
}
function deserialise(raw) {
  const room = raw;
  room.game.flags = new Set(room.game.flags);
  return room;
}
async function readRoom(code) {
  const res = await rest(`rooms?code=eq.${code}&select=state,revision`);
  if (!res.ok) return null;
  const rows = await res.json();
  if (!rows.length) return null;
  return { room: deserialise(rows[0].state), revision: rows[0].revision };
}
async function writeRoom(room, revision) {
  const next = revision + 1;
  const res = await rest(`rooms?code=eq.${room.code}&revision=eq.${revision}`, {
    method: "PATCH",
    headers: { Prefer: "return=representation" },
    body: JSON.stringify({ state: serialise(room), revision: next, updated_at: (/* @__PURE__ */ new Date()).toISOString() })
  });
  if (!res.ok) return null;
  const rows = await res.json();
  return rows.length ? next : null;
}
async function withRoom(code, mutate) {
  for (let attempt = 0; attempt < 5; attempt++) {
    const loaded = await readRoom(code);
    if (!loaded) return null;
    const next = mutate(loaded.room);
    const revision = await writeRoom(next, loaded.revision);
    if (revision !== null) return { room: next, revision };
  }
  return null;
}
async function broadcastRevision(code, revision) {
  await fetch(`${SUPABASE_URL}/realtime/v1/api/broadcast`, {
    method: "POST",
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      messages: [{ topic: `room:${code}`, event: "rev", payload: { revision } }]
    })
  }).catch(() => {
  });
}
async function seatForToken(code, token) {
  const res = await rest(`room_seats?code=eq.${code}&token=eq.${token}&select=role`);
  if (!res.ok) return null;
  const rows = await res.json();
  return rows.length ? rows[0].role : null;
}
function viewFor(room, seat) {
  const finished = room.phase === "results" || room.phase === "ended";
  const end = finished ? endgame(room, content) : null;
  return seat === "dashboard" ? { kind: "dashboard", view: dashboardView(room, content), endgame: end } : { kind: "phone", view: phoneView(room, content, seat), endgame: end };
}
function roster(room) {
  return ROLES.map((role) => ({
    role,
    name: room.players[role].name || null,
    taken: Boolean(room.players[role].name)
  }));
}
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "POST only" }, 405);
  let body;
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad json" }, 400);
  }
  const action = String(body.action ?? "");
  const now = Date.now();
  if (action === "create") {
    const seed = Math.floor(Math.random() * 2 ** 31);
    let room2 = createRoom(content, seed, now);
    for (let attempt = 0; attempt < 8; attempt++) {
      const res = await rest("rooms", {
        method: "POST",
        headers: { Prefer: "return=minimal" },
        body: JSON.stringify({ code: room2.code, state: serialise(room2), revision: 1 })
      });
      if (res.ok) break;
      if (res.status !== 409) return json({ error: "could not create room" }, 500);
      room2 = createRoom(content, seed + attempt + 1, now);
      if (attempt === 7) return json({ error: "no free room code" }, 503);
    }
    const seat2 = await rest("room_seats", {
      method: "POST",
      headers: { Prefer: "return=representation" },
      body: JSON.stringify({ code: room2.code, role: "dashboard" })
    });
    const rows = await seat2.json();
    return json({ code: room2.code, token: rows[0].token, ...viewFor(room2, "dashboard"), revision: 1 });
  }
  const code = String(body.code ?? "").toUpperCase();
  if (!/^[A-Z]{4}$/.test(code)) return json({ error: "bad room code" }, 400);
  if (action === "claim") {
    const role = String(body.role ?? "");
    if (!ROLES.includes(role)) return json({ error: "unknown seat" }, 400);
    const existing = await readRoom(code);
    if (!existing) return json({ error: "no such room" }, 404);
    const held = await rest(`room_seats?code=eq.${code}&role=eq.${role}&select=token`);
    const heldRows = await held.json();
    if (heldRows.length) {
      if (existing.room.players[role].name) {
        return json({ error: "seat taken", seats: roster(existing.room) }, 409);
      }
      return json({ token: heldRows[0].token, ...viewFor(existing.room, role), revision: existing.revision });
    }
    const res = await rest("room_seats", {
      method: "POST",
      headers: { Prefer: "return=representation" },
      body: JSON.stringify({ code, role })
    });
    if (!res.ok) return json({ error: "seat taken" }, 409);
    const rows = await res.json();
    return json({ token: rows[0].token, ...viewFor(existing.room, role), revision: existing.revision });
  }
  const token = String(body.token ?? "");
  const seat = token ? await seatForToken(code, token) : null;
  if (!seat) return json({ error: "not your seat" }, 403);
  const loaded = await readRoom(code);
  if (!loaded) return json({ error: "no such room" }, 404);
  let { room, revision } = loaded;
  if (action === "view") {
    return json({ ...viewFor(room, seat), revision });
  }
  if (action === "tick") {
    if (room.pausedAt != null || room.phaseEndsAt === null || Date.now() < room.phaseEndsAt) {
      return json({ ...viewFor(room, seat), revision });
    }
    const written = await withRoom(code, (r) => tick(r, content, Date.now()));
    if (!written) return json({ ...viewFor(room, seat), revision });
    await broadcastRevision(code, written.revision);
    return json({ ...viewFor(written.room, seat), revision: written.revision });
  }
  if (action === "release") {
    if (seat === "dashboard") return json({ error: "the big screen holds no seat" }, 403);
    const written = await withRoom(code, (r) => apply(r, { t: "leave", role: seat }, content, Date.now()));
    await rest(`room_seats?code=eq.${code}&token=eq.${token}`, { method: "DELETE" });
    if (written) await broadcastRevision(code, written.revision);
    return json({ ok: true, revision: written?.revision ?? revision });
  }
  if (action === "cmd") {
    const requested = body.cmd;
    const allowed = requested ? authorise(seat, requested) : null;
    if (!allowed) return json({ error: "not allowed from this seat" }, 403);
    const written = await withRoom(code, (r) => apply(r, allowed, content, Date.now()));
    if (!written) return json({ error: "the room is busy \u2014 try again" }, 503);
    await broadcastRevision(code, written.revision);
    return json({ ...viewFor(written.room, seat), revision: written.revision });
  }
  return json({ error: "unknown action" }, 400);
});
